<?php
/**
 * @file
 * Code for the ImageX Content Likes feature.
 */

include_once 'imagex_content_likes.features.inc';

/**
 * Implements hook_permission()
 *
 * Add custom permission to turn off "Who Liked This" node tab
 */
function imagex_content_likes_permission() {
  return array(
    'view liked counter' => array(
      'title' => t('View liked counter'),
    ),
    'view who liked this node tab' => array(
      'title' => t('View who liked this node tab'),
    ),
  );
}

/**
 * Implements hook_views_access_callbacks().
 */
function imagex_content_likes_views_access_callbacks() {
  return array(
    'imagex_content_likes_user_has_access' => t('ImageX Content Likes: Access - permissions and likes'),
  );
}

/**
 * Views Access Callback.
 */
function imagex_content_likes_user_has_access($nid) {
  $num_of_likes = imagex_content_likes_get_flag_counts_by_entity($nid);
  return user_access('view who liked this node tab') && $num_of_likes > 0;
}

/**
 * Implements hook_theme_registry_alter()
 *
 * Make flag look at our flag.tpl.php
 */
function imagex_content_likes_theme_registry_alter(&$theme_registry) {
  $theme_registry['flag']['path'] = drupal_get_path('module', 'imagex_content_likes');
}

/**
 * Implements template_preprocess_flag()
 *
 * Add a new $flag_counter text/link
 *
 * Example use in flag.tpl.php:
 * <?php if (!empty($flag_counter)) { ?>
 *   (<span class="flag-counter"><?php echo $flag_counter; ?></span>)
 * <?php }; ?>
 */
function imagex_content_likes_preprocess_flag(&$variables) {
  global $user;

  // vars
  $flag = &$variables['flag'];
  $action = $variables['action'];
  $entity_id = $variables['entity_id'];
  $variables['flag_counter'] = '';
  
  //check the flag in question & permissions
  if ($flag->name == 'imagex_node_like' && user_access('view liked counter')) {
    $flag_counter_raw = $flag->get_count($entity_id);
    $flag_counter = format_plural($flag_counter_raw, '1 like', '@count likes');
    
    //link to node/%/likes?
    if (user_access('view who liked this node tab') && $flag_counter_raw > 0) {
      $flag_counter = l($flag_counter, 'node/'. $entity_id .'/likes', array('attributes' => array('title' => t('View who liked this'))));
    }
    $variables['flag_counter'] = $flag_counter;
  }
}

/**
 * Retrieves the number of likes for the specified entity.
 *
 * @param int $entity_id
 *   The entity to retrieve the number of likes for.
 * @return mixed
 *   The total number of likes.
 */
function imagex_content_likes_get_flag_counts_by_entity($entity_id) {
  $flag_counts = &drupal_static(__FUNCTION__, array());
  if (!isset($flag_counts[$entity_id])) {
    $flag = flag_get_flag('imagex_node_like');
    $flag_counts[$entity_id] = db_select('flag_counts', 'fc')
      ->fields('fc', array('flagging_id'))
      ->condition('fid', $flag->fid)
      ->condition('entity_id', $entity_id)
      ->countQuery()
      ->execute()
      ->fetchField();
  }
  return $flag_counts[$entity_id];
}
